<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="182065" started-at="2018-09-11T05:13:00Z" finished-at="2018-09-11T05:16:02Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="182065" started-at="2018-09-11T05:13:00Z" finished-at="2018-09-11T05:16:02Z">
      <class name="Tests.DepositTest">
        <test-method status="PASS" signature="runDriver()[pri:0, instance:Tests.DepositTest@5bc79255]" name="runDriver" is-config="true" duration-ms="29962" started-at="2018-09-11T10:45:05Z" finished-at="2018-09-11T10:45:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runDriver -->
        <test-method status="FAIL" signature="successfulDeposit()[pri:0, instance:Tests.DepositTest@5bc79255]" name="successfulDeposit" duration-ms="20128" started-at="2018-09-11T10:45:35Z" finished-at="2018-09-11T10:45:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at org.testng.Assert.assertEquals(Assert.java:296)
	at Tests.DepositTest.successfulDeposit(DepositTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- successfulDeposit -->
        <test-method status="PASS" signature="close()[pri:0, instance:Tests.DepositTest@5bc79255]" name="close" is-config="true" duration-ms="417" started-at="2018-09-11T10:46:01Z" finished-at="2018-09-11T10:46:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- Tests.DepositTest -->
      <class name="ListenersClass.TestListner">
        <test-method status="PASS" signature="setupChromeDriver()[pri:0, instance:ListenersClass.TestListner@7b49cea0]" name="setupChromeDriver" is-config="true" duration-ms="18" started-at="2018-09-11T10:42:59Z" finished-at="2018-09-11T10:43:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupChromeDriver -->
      </class> <!-- ListenersClass.TestListner -->
      <class name="Tests.NewCustomerTest">
        <test-method status="PASS" signature="runDriver()[pri:0, instance:Tests.NewCustomerTest@3dd4520b]" name="runDriver" is-config="true" duration-ms="31373" started-at="2018-09-11T10:43:00Z" finished-at="2018-09-11T10:43:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runDriver -->
        <test-method status="FAIL" signature="successfulCustomerAdd()[pri:0, instance:Tests.NewCustomerTest@3dd4520b]" name="successfulCustomerAdd" duration-ms="27208" started-at="2018-09-11T10:43:31Z" finished-at="2018-09-11T10:43:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at org.testng.Assert.assertEquals(Assert.java:296)
	at Tests.NewCustomerTest.successfulCustomerAdd(NewCustomerTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- successfulCustomerAdd -->
        <test-method status="PASS" signature="close()[pri:0, instance:Tests.NewCustomerTest@3dd4520b]" name="close" is-config="true" duration-ms="360" started-at="2018-09-11T10:44:03Z" finished-at="2018-09-11T10:44:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- Tests.NewCustomerTest -->
      <class name="Tests.LoginTest">
        <test-method status="PASS" signature="runDriver()[pri:0, instance:Tests.LoginTest@23e028a9]" name="runDriver" is-config="true" duration-ms="27603" started-at="2018-09-11T10:44:03Z" finished-at="2018-09-11T10:44:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runDriver -->
        <test-method status="PASS" signature="setup()[pri:0, instance:Tests.LoginTest@23e028a9]" name="setup" is-config="true" duration-ms="0" started-at="2018-09-11T10:44:31Z" finished-at="2018-09-11T10:44:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="invalidUsernamePassword()[pri:0, instance:Tests.LoginTest@23e028a9]" name="invalidUsernamePassword" duration-ms="3791" started-at="2018-09-11T10:44:31Z" finished-at="2018-09-11T10:44:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidUsernamePassword -->
        <test-method status="PASS" signature="invalidUsernameValidPassword()[pri:0, instance:Tests.LoginTest@23e028a9]" name="invalidUsernameValidPassword" duration-ms="10227" started-at="2018-09-11T10:44:35Z" finished-at="2018-09-11T10:44:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidUsernameValidPassword -->
        <test-method status="PASS" signature="validUsernameInvalidPassword()[pri:0, instance:Tests.LoginTest@23e028a9]" name="validUsernameInvalidPassword" duration-ms="6228" started-at="2018-09-11T10:44:45Z" finished-at="2018-09-11T10:44:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUsernameInvalidPassword -->
        <test-method status="PASS" signature="validUsernamePassword()[pri:0, instance:Tests.LoginTest@23e028a9]" name="validUsernamePassword" duration-ms="13844" started-at="2018-09-11T10:44:51Z" finished-at="2018-09-11T10:45:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUsernamePassword -->
        <test-method status="PASS" signature="close()[pri:0, instance:Tests.LoginTest@23e028a9]" name="close" is-config="true" duration-ms="406" started-at="2018-09-11T10:45:05Z" finished-at="2018-09-11T10:45:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- Tests.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
